# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format
  entry: hooks/terraform-fmt.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files
  entry: hooks/terraform-validate.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: terraform-docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: hooks/terraform-docs.sh
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: tflint
  name: TFlint
  description: Linter for Terraform source code
  entry: hooks/tflint.sh
  language: script
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: tfsec
  name: TFsec
  description: Static analysis of Terraform templates to spot potential security issues.
  entry: hooks/tfsec.sh
  language: script

- id: shellcheck
  name: shellcheck
  description: Performs linting on bash scripts
  entry: hooks/shellcheck.sh
  language: script

- id: bandit
  name: bandit
  description: 'Bandit is a tool for finding common security issues in Python code'
  entry: bandit
  language: python
  language_version: python3
  types: [python]

- id: flake8
  name: flake8
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: flake8
  language: python
  types: [python]
  require_serial: true

- id: black
  name: black
  description: "Black: The uncompromising Python code formatter"
  entry: black
  language: python
  language_version: python3
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]

- id: hadolint
  name: Lint Dockerfiles
  description: Runs hadolint to lint Dockerfiles
  language: system
  entry: hadolint
  files: Dockerfile

- id: docker-black
  name: docker-black
  language: docker_image
  entry: --entrypoint black louisjyng/js-pre-commit:latest
  files: \.py$

- id: docker-flake8
  name: docker-flake8
  language: docker_image
  entry: --entrypoint flake8 louisjyng/js-pre-commit:latest
  files: \.py$

- id: docker-tflint
  name: docker-tflint
  language: docker_image
  entry: --entrypoint /hooks/tflint.sh louisjyng/js-pre-commit:latest
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: docker-tfsec
  name: docker-tfsec
  language: docker_image
  entry: --entrypoint /hooks/tfsec.sh louisjyng/js-pre-commit:latest

- id: docker-shellcheck
  name: docker-shellcheck
  language: docker_image
  entry: --entrypoint /hooks/shellcheck.sh louisjyng/js-pre-commit:latest

- id: docker-terraform-fmt
  name: docker-terraform-fmt
  language: docker_image
  entry: --entrypoint /hooks/terraform-fmt.sh louisjyng/js-pre-commit:latest
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: docker-terraform-validate
  name: docker-terraform-validate
  language: docker_image
  entry: --entrypoint /hooks/terraform-validate.sh louisjyng/js-pre-commit:latest
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: docker-terraform-docs
  name: docker-terraform-docs
  language: docker_image
  entry: --entrypoint /hooks/terraform-docs.sh louisjyng/js-pre-commit:latest
  files: \.tf$
  exclude: \.+.terraform\/.*$
